#!/bin/dash

# /etc/init.d/dropbear: a Dropbear init script

# the pidfile path
PIDFILE_PATH="/var/run/dropbear/dropbear.pid"

case "$1" in

	start)
		echo -n "Starting Dropbear ..."
	
		# generate the keys
		for i in rsa dss
		do
			[ -f /etc/dropbear/dropbear_${i}_host_key ] && continue
			dropbearkey -t $i -f /etc/dropbear/dropbear_${i}_host_key
			if [ $? -ne 0 ]
			then
				echo "Error: failed to generate the $(echo $i | tr \[:lower:\] \[:upper:\]) key."
				exit 1
			fi
			chown ssh:ssh /etc/dropbear/dropbear_${i}_host_key
			chmod 600 /etc/dropbear/dropbear_${i}_host_key
		done

		# create a directory for the pidfile
		[ ! -d /var/run/dropbear ] && mkdir /var/run/dropbear
		chown ssh:ssh /var/run/dropbear
		chmod 755 /var/run/dropbear

		# include the configuration file
		. /etc/init.conf/dropbear

		# start the server
		su -c "dropbear -P $PIDFILE_PATH $ADDITIONAL_OPTS" ssh
		echo " done"
		exit $?
		;;

	stop)
		echo -n "Stopping Dropbear ..."
		kill $(cat $PIDFILE_PATH)
		success=$?
		rm -f $PIDFILE_PATH
		echo " done"
		exit $success
		;;

	restart)
		"$0" stop
		"$0" start
		;;

	*)
		echo "dropbear {start|stop|restart}"
		exit 1
		;;

esac
