#!/bin/dash

# /etc/init.d/bitlbee: an init script for BitlBee

case "$1" in

	start)
		echo -n "Starting BitlBee ..."
		[ -f /var/run/bitlbee ] && rm -f /var/run/bitlbee
		bitlbee -D
		success=$?
		echo " done"
		exit $success
		;;

	stop)
		echo -n "Stopping BitlBee ..."
		kill $(pidof bitlbee)
		success=$?
		rm -f /var/run/bitlbee
		echo " done"
		exit $success
		;;

	restart)
		"$0" stop
		"$0" start
		;;

	*)
		echo "bitlbee {start|stop|restart}"
		exit 1
		;;

esac
