#!/bin/dash

# /etc/init.d/firewall: a basic firewall
# dependencies: dash and iptables

case "$1" in

	start)
		echo -n "Starting firewall ..."
	
		# include the configuration file
		. /etc/init.conf/firewall

		# remove the current configuration
		iptables -F
		iptables -X

		# create two chains
		iptables -N TCP
		iptables -N UDP

		# disble NAT
		iptables -P FORWARD DROP

		# allow all outgoing traffic
		iptables -P OUTPUT ACCEPT

		# drop all incoming traffic
		iptables -P INPUT DROP

		# accept all incoming traffic in the loopback interface
		iptables -A INPUT -i lo -j ACCEPT

		# allow established connections and related ICMP traffic
		iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

		# drop invalid connections
		iptables -A INPUT -m conntrack --ctstate INVALID -j DROP

		# accept IPv6 Neighbor Discovery packets
		iptables -A INPUT -p 41 -j ACCEPT

		# drop SYN packets, we don't like being scanned
		iptables -A INPUT -p tcp --syn -m conntrack --ctstate NEW -j TCP

		# totally ignore ICMP echo requests
		echo 1 > /proc/sys/net/ipv4/icmp_echo_ignore_all

		# accept TCP connections to certain ports
		for port in $TCP_ALLOW
		do
			iptables -A TCP -p tcp --dport $port -j ACCEPT
		done

		# ... same for UDP
		for port in $UDP_ALLOW
		do
			iptables -A UDP -p udp --dport $port -j ACCEPT
		done

		echo " done"
		;;

	stop)
		echo -n "Stopping firewall ..."

		# remove the current configuration
		iptables -F
		iptables -X
		for chain in INPUT FORWARD OUTPUT
		do
			iptables -P $chain ACCEPT
		done

		echo " done"
		;;

	restart)
		"$0" stop
		"$0" start
		;;

	*)
		echo "firewall {start|stop|restart}"
		exit 1
		;;

esac
