#!/bin/dash

# /etc/init.d/dbus: an init script for D-Bus

case "$1" in
	start)
		echo -n "Starting D-Bus ..."
		[ -f /run/dbus/dbus.pid ] && rm -f /run/dbus/dbus.pid
		dbus-daemon --system --fork
		exit_code=$?
	 	dbus-uuidgen > /var/lib/dbus/machine-id
	 	echo " done"
		exit $exit_code
		;;

	stop)
		echo -n "Stopping D-Bus ..."
		kill $(cat /run/dbus/dbus.pid)
		exit_code=$?
		echo " done"
		exit $exit_code
		;;
		
	restart)
		"$0" stop
		"$0" start
		;;

	*)
		echo "dbus {start|stop|restart}"
		exit 1
		;;
esac
