#!/bin/dash

# /sbin/create_save_file: a save file creation tool
# dependencies: dash and file system tools for the save file's file system

# the command-line usage message
USAGE="create_save_file PATH

Creates a system save file, for persistency."

# check the command-line arguments
if [ 1 -ne $# ] || [ -e "$1" ]
then
	echo "$USAGE"
	exit 1
fi

# include the boot configuration
. /etc/bootrc

# let the user choose the save file size
while [ true ]
do
	read -p "Save file size (MB): " save_file_size
	case "$save_file_size" in
		""|*[!0-9]*)
			continue
			;;
		*)
			break
			;;
	esac
done

# create an empty save file
echo -n "Creating the save file ..."
dd if=/dev/zero of="$1" bs=1024 count=${save_file_size}000 > /dev/null 2>&1
if [ 0 -ne $? ]
then
	[ -f "$1" ] && rm -f "$1"
	echo
	echo "Error: failed to create the save file"
	exit 1
fi
echo " done"

# create a file system inside the save file
echo -n "Creating a file system ..."
mkfs.$SAVE_FILE_FS -F "$1" > /dev/null 2>&1
if [ 0 -ne $? ]
then
	rm -f "$1"
	echo
	echo "Error: failed to create a file system in the save file."
	exit 1
fi
echo " done"
