#!/bin/dash

# /init: a system init script
# dependencies: dash and busybox

# files to load into the page cache
FILES_TO_PRELOAD="/bin/dash /bin/busybox"

# the size of the tmpfs file system used as the writeable layer, if no save file
# is used
TMPFS_SIZE="75%"

# the directory containing the kernel, the initramfs and other files required to
# boot the system
BOOT_DIR="boot"

# the main Squashfs image path
MAIN_SFS_NAME="rootfs.sfs"

# usage: show_error $error
show_error()
{
	echo
	echo "Error: $1"
	sleep 20
	exit 0
}

# clear the screen
clear

# set the executable search path
export PATH="/bin:/sbin:/usr/bin:/usr/sbin"

# preload all frequently executed binaries
for file in $FILES_TO_PRELOAD
do
	readahead $file
done

# mount all virtual file systems
mount -t rootfs -o remount,rw rootfs /
mount -t proc proc /proc
mount -t sysfs sysfs /sys

# the session is non-persistent, unless the "parsistent" boot code was passed
is_persistent=0

# parse the kernel command-line
for argument in $(cat /proc/cmdline)
do
	case "$argument" in
		root=*)
			root="${argument#*=}"
			;;
		sleep=*)
			sleep="${argument#*=}"
			;;
		persistent)
			is_persistent=1
			;;
	esac
done

# make sure a root partition was specified
[ -z "$root" ] && show_error "no root partition was specified"

# if the "sleep" argument was passed, sleep for the given number of seconds
case "$sleep" in
	[0-9]*)
		echo -n "Sleeping for $sleep second(s) ..."
		sleep $sleep
		echo " done"
		;;
esac

# generate device nodes for all recognized partitions
mdev -s

# if the root partition was specified through its UUID, determine its name
case "$root" in
	*-*-*-*-*)
		root="$(blkid | \
		        grep UUID=\"$root\" | \
		        cut -f 1 -d : | cut -f 3- -d /)"
		[ -z "$root" ] && show_error "the given UUID was not found"
		;;
esac

# mount the root partition
mount /dev/$root /mnt/root
[ 0 -ne $? ] && show_error "failed to mount the root partition"

# mount the main Squashfs image, located under the root partition
mount /mnt/root/$BOOT_DIR/$MAIN_SFS_NAME /mnt/ro -t squashfs -o loop,ro
[ 0 -ne $? ] && show_error "failed to mount the main file system image"

# prepare a writeable file system
if [ 0 -eq $is_persistent ]
then
	# under non-persistent mode, use a tmpfs file system
	mount -t tmpfs -o size=$TMPFS_SIZE,rw tmpfs /mnt/rw
	[ 0 -ne $? ] && show_error "failed to mount a tmpfs file system"
else
	# under persistent mode, use the root partition
	mount --bind /mnt/root /mnt/rw
	[ 0 -ne $? ] && show_error "failed to bind the root partition"
fi

# create a union of the writeable file system and the main Squashfs image
mount -t aufs -o br=/mnt/rw=rw:/mnt/ro=ro aufs /mnt/union
[ 0 -ne $? ] && show_error "failed to set up the layered file system"

# move all mounted file systems to the union file system's /mnt
for file_system in ro rw root
do
	mkdir -p /mnt/union/mnt/$file_system
	mount --move /mnt/$file_system /mnt/union/mnt/$file_system
	[ 0 -ne $? ] && show_error "failed to set up the layered file system"
done

# if /boot doesn't exist, create a symlink to the root partition's
[ ! -e "/mnt/union/$BOOT_DIR" ] && \
                                  ln -s /mnt/root/$BOOT_DIR /mnt/union/$BOOT_DIR

# unmount virtual file systems
umount /proc
umount /sys

# switch to the union file system
exec switch_root /mnt/union /sbin/init
show_error "failed to switch to the layered file system"
