#!/bin/sh

# usage: convert_package_list $package_list $repository_name

# include the distribution parameters file
. ./distro/opensuse/parameters

# OpenSUSE repositories contain packages for all architectures - filter only
# those of the target one
./distro/centos/convert_package_list $1 $2 | grep \|$arch/
