#!/bin/sh

# usage: extract_package $package $dest

# create the output directory
mkdir -p "$2"

# convert the RPM package to a CPIO archive and extract it
cd "$2"
rpm2cpio "$1" | cpio -id
[ 0 -ne $? ] && exit 1

exit 0
