#!/bin/dash

# /etc/X11/xinit/xinitrc: a startup script for the X server
# dependencies: dash and hsetroot

delayed_run()
{
	sleep 2

	# start desktop applications
	if [ -d ~/Startup ]
	then
		for i in ~/Startup/*
		do
			[ -x "$i" ] && $i &
		done
	fi
}

# include the default configuration file
. /etc/desktoprc

# include the user's configuration file
[ -f ~/.desktoprc ] && . ~/.desktoprc

# set the desktop background
if [ ! -f "/usr/share/backgrounds/$DESKTOP_BG" ]
then
	bg="/usr/share/backgrounds/$DEFAULT_DESKTOP_BG"
else
	bg="/usr/share/backgrounds/$DESKTOP_BG"
fi

if [ -z "$DESKTOP_BG_MODE" ]
then
	mode="$DEFAULT_DESKTOP_BG_MODE"
else
	mode="$DESKTOP_BG_MODE"
fi

hsetroot -$mode "$bg" &

# start all startup applications
delayed_run &

# execute the window manager
if [ -n "$WINDOW_MANAGER" ]
then
	exec $WINDOW_MANAGER
else
	exec $DEFAULT_WINDOW_MANAGER
fi


