#!/bin/dash

# /etc/X11/xinit/xinitrc: a startup script for the X server
# dependencies: dash and hsetroot

delayed_run()
{
	sleep 2

	# start desktop applications
	if [ -d ~/Startup ]
	then
		for i in ~/Startup/*
		do
			[ -x "$i" ] && $i &
		done
	fi
}

# include the user's configuration file
. ~/.desktoprc

# set the desktop background
hsetroot -$DESKTOP_BG_MODE "/usr/share/backgrounds/$DESKTOP_BG" &

# start all startup applications
delayed_run &

# execute the window manager
exec $WINDOW_MANAGER