#!/bin/dash

# /etc/init.d/fluidsynth: a FluidSynth init script

# include the configuration file
. /etc/init.conf/fluidsynth

case "$1" in

	start)
		echo -n "Starting FluidSynth ..."
		. /etc/init.conf/fluidsynth
		fluidsynth -s -i -a alsa $ADDITIONAL_OPTS $SOUND_FONT > /dev/null 2>&1 &
		pidof fluidsynth > /var/run/fluidsynth.pid
		echo " done"
		;;

	stop)
		echo -n "Stopping FluidSynth ..."
		kill $(cat /var/run/fluidsynth.pid)
		success=$?
		rm -f /var/run/fluidsynth.pid
		echo " done"
		exit $success
		;;

	restart)
		"$0" stop
		"$0" start
		;;

	*)
		echo "fluidsynth {start|stop|restart}"
		exit 1
		;;

esac
